services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: development
      DB_FILENAME: "/kutt/db/data.sqlite"
    volumes:
      - ./custom:/kutt/custom  # ✅ bind-mount your real local folder
      - ./kutt-sqlite-data:/kutt/db # store the db file in real local folder
    ports:
      - 3000:3000  # Internal, proxied via Nginx
    command: >
      sh -c "
        echo '🚀 Starting Kutt in dev mode...';
        npm run migrate && npm run dev
      "
    env_file:
      - .dev.env
    restart: unless-stopped

  caddy:
    image: caddy:alpine
    restart: unless-stopped
    depends_on:
      server:
        condition: service_started
    ports:
      - "8025:8025"
      - "443:443"
    volumes:
      - ./Caddyfile.dev:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  db_data_sqlite:
  caddy_data:
  caddy_config:
